# tefnut — the third house box, and the one with NO JOB YET.
#
# Named for shu's twin. Storage-class rather than a Kubernetes node, on a home
# LAN behind the router, no public address, wifi, one-way VPN peer admitting
# only the Mac — the shape geb and shu already share.
#
# ⚠ THIS IS THE FIRST HOUSE BOX THAT IS ACTUALLY geb's TWIN. Same Quieter 4C
# board, same `Rev TWL6-DDR4 1.10`, same `ML_TWL6 V11.7` BIOS, same N150, same
# 31 GiB, same `wlp0s20f3` — and its generated hardware-configuration.nix
# differs from geb's ONLY in the two filesystem UUIDs. shu looked like a twin
# and was not (sold as an N150, actually an i3-6006U), so this was read off the
# DMI rather than inferred. Everything geb does about its hardware applies here
# unchanged; nothing shu does about ITS hardware necessarily does.
#
# ⚠ WHAT IT IS FOR IS NOT DECIDED, and that is the honest state rather than an
# unfinished edit. geb was installed with no job on 2026-08-10 and got one two
# days later; its own file is explicit that a job gets DECIDED rather than
# inherited from what the disk used to hold. Until there is one, this file
# contains only what every house box needs and nothing speculative.
#
# Everything below undoes an assumption in base-configuration.nix (three rented
# BIOS-boot machines with public addresses and a Kubernetes cluster), and every
# one of them is a line geb and shu needed too.

{ config, pkgs, lib, ... }:

{
  imports = [
    ../../base-configuration.nix
  ];

  # ⚠ NO PLAN, AND UNLIKE shu THAT IS A GAP RATHER THAN A DECISION. shu's file
  # says "no other plan" because the one plan it runs is the one it can answer.
  # Here there is no plan at all, so tefnut's one-way block — generated by the
  # `oneWay` flag in network.nix, same as geb's and shu's — is judged by
  # NOTHING on this machine.
  #
  # Deliberately staged, not forgotten: a new fleetwatch producer also needs a
  # per-machine ingest token minted on isis, and enabling the plan without one
  # turns the row red rather than green (#1403). Landing the base config first
  # means a failure here names the base config. See #1469.

  # UEFI, not BIOS. base-configuration sets `boot.loader.grub.device` for the
  # OVH machines. Verified at install rather than assumed: /sys/firmware/efi
  # was present, efivars mounted, fw_platform_size 64.
  #
  # ⚠ The firmware boots USB before the internal disk, and offers no obvious
  # way to say otherwise from the one-shot menu — F7 picks the NVMe for one
  # boot only. A stick left plugged in takes over the boot silently, which on a
  # headless box reads as "it did not come back up".
  boot.loader.grub.enable = lib.mkForce false;
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Installed on 26.05, 2026-09-06. The fleet-wide 21.11 in base-configuration is
  # amun's install version; stateVersion pins the stateful defaults a machine was
  # BUILT with, and claiming 21.11 on a disk formatted in 2026 asserts a
  # migration history it does not have.
  system.stateVersion = lib.mkForce "26.05";

  # Wifi only, so NetworkManager owns the link and the connection profile is
  # machine state in /etc/NetworkManager/system-connections — deliberately NOT a
  # declarative networking.wireless block, which would want the PSK in a Nix
  # file and this repository is public.
  #
  # ⚠ ONE PROFILE TODAY (5 GHz), where shu has a 2.4 GHz fallback behind it. shu
  # is a floor up and needed one. Whether tefnut does is a question about where
  # it ends up sitting, so it is left until that is known rather than copied
  # across on the assumption that the two boxes live in the same place.
  networking.networkmanager.enable = true;

  # ⚠ Both NetworkManager and base-configuration define this as plain
  # definitions, so the module system cannot pick one and evaluation fails
  # outright rather than warning. mkForce settles it in NetworkManager's favour.
  networking.useDHCP = lib.mkForce false;

  # The iwlwifi adapter does not exist without this, the connection profile has
  # nothing to bind to, and there is no cable to fall back on. Same part as
  # geb's, so same requirement.
  hardware.enableRedistributableFirmware = true;

  # base-configuration points every host at kube-dns (10.43.0.10) and OVH's
  # resolver: the first is a cluster service IP not routed over WireGuard, so it
  # is a dead first query on every lookup, and the second is only near the
  # rented machines. Let NetworkManager write resolv.conf from DHCP.
  networking.nameservers = lib.mkForce [ ];

  # Not a build node. base-configuration runs a buildfarm worker on every host,
  # mounting ~/.config/buildfarm/${config.node.name}.yml — a file tefnut has no
  # reason to have, so the container would restart-loop indefinitely.
  virtualisation.oci-containers.containers = lib.mkForce { };

  # ⚠ NO BLUETOOTH BLOCK, deliberately. geb and shu both enable it because both
  # are Govee receivers. Enabling a radio on a box with nothing to do with it
  # would be config written for a job that has not been assigned.
}
