#!/usr/bin/env python3
"""Render clusters.dhall: each k3s node's edge, from network.nix.

The kubes model (the home monorepo's code/kubes/dhall) needs to know how each
cluster is reached from outside, because a NetworkPolicy admitting the ingress-nginx
namespace selects nothing where the edge is the host front door. It used to
state that itself (`isis = False, amun = True`), a second copy of a fact this
repository owns. It now reads a committed copy of this file, and fleet_health
checks the two copies agree, the same arrangement as frontdoor.json in reverse.

    scripts/render_clusters.py           write clusters.dhall
    scripts/render_clusters.py --check   fail if it is stale (the gate row)
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "clusters.dhall"

# Dhall labels cannot hold a hyphen unquoted, and the model merges on these.
CONSTRUCTOR = {"frontdoor": "Frontdoor", "ingress-nginx": "IngressNginx"}


def edges() -> dict[str, str]:
    """Every node with an edge, by its own name. `master` aliases amun, so a
    node is read under the key that IS its name and never twice."""
    out = subprocess.run(
        ["nix-instantiate", "--eval", "--strict", "--json", "-E", "(import ./network.nix).nodes"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    nodes = json.loads(out)
    return {k: n["edge"] for k, n in sorted(nodes.items()) if n.get("name") == k and n.get("edge")}


def render(by_node: dict[str, str]) -> str:
    fields = ", ".join(f"{name} = Edge.{CONSTRUCTOR[edge]}" for name, edge in by_node.items())
    return (
        "-- GENERATED by nixos-config/scripts/render_clusters.py from network.nix.\n"
        "-- Do not edit; the kubes model keeps a copy (see that script).\n"
        "let Edge = < Frontdoor | IngressNginx >\n"
        "\n"
        f"in  {{ Edge, clusters = {{ {fields} }} }}\n"
    )


def main() -> int:
    text = render(edges())
    if sys.argv[1:] == ["--check"]:
        if not OUT.is_file() or OUT.read_text() != text:
            print("clusters.dhall is stale: run scripts/render_clusters.py", file=sys.stderr)
            return 1
        print(f"clusters.dhall matches network.nix ({text.count('Edge.')} cluster(s))")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
