#!/usr/bin/env bash
# nixos-config verify — the repo's gate. Run it, or let the fleet run it:
#
#   ./scripts/verify.sh                       (what `~/Code/check --full` does)
#
# The real check here is the EVAL: every machine's complete NixOS configuration is
# evaluated (module system, agenix, home-manager, every option definition), which is
# what catches a removed package, a renamed option, or a typo'd attribute — the class
# of breakage you otherwise discover halfway through a `nixos-rebuild switch` on the
# host. It evaluates only; nothing is built, so it runs on the Mac.
#
# Two things a host has that a clean checkout does not, both reconstructed below:
#   configuration.nix           generated by setup.sh from configuration.nix.dist
#   hardware-configuration.nix  the machine's own, at the repo ROOT (base-configuration
#                               imports ./hardware-configuration.nix relative to itself)
# Both are gitignored because they are per-host. The per-machine hardware files ARE
# tracked, so the layout is reproducible: pick the machine's, drop it at the root.
#
# The password is a dummy: setup.sh interpolates a real hash from `mkpasswd`, and the
# eval only needs the option to typecheck as a string. No secret is involved.
#
# NIX_PATH (nixpkgs + home-manager) comes from the devshell — see flake.nix. The
# machines are still channel-based in production; pinning here only makes the GATE
# reproducible, and it is why amun's EOL k3s pin shows up as a failure rather than
# silently depending on which channel the checking machine happens to have.
#
# dev-lint: allow-no-strict-mode — this is an aggregating gate: it runs every step,
# records failures in $fail, and exits non-zero at the end, so it deliberately omits
# `-e` (which would abort at the first failing step and hide the rest).
set -uo pipefail

# The pinned toolchain lives in nix/, NOT at the repo root: the root is /etc/nixos on
# each host, and nixos-rebuild would take a root flake.nix as the system to build (see
# nix/flake.nix). So this gate enters its own devshell rather than relying on the
# caller to do it — `~/Code/check` runs the gate of a repo with no root flake directly.
here="$(cd "$(dirname "$0")" && pwd)"
if [ -z "${NIXOS_CONFIG_DEVSHELL:-}" ]; then
  exec nix --extra-experimental-features "nix-command flakes" \
    develop "path:$here/../nix" -c \
    env NIXOS_CONFIG_DEVSHELL=1 "$here/verify.sh" "$@"
fi

# `|| exit` matters here: this gate deliberately omits `set -e` (see above), so a
# failed cd would otherwise run every check against the wrong directory.
cd "$here/.." || exit 1
fail=0
step() { printf '\n▸ %s\n' "$1"; }

# All three machines are x86_64 Linux; we are (usually) evaluating from an aarch64
# Mac, so the system has to be named explicitly or Nix assumes the host's.
readonly SYSTEM=x86_64-linux

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
cp -R . "$work/" && rm -rf "$work/.git"

step "nix eval — every machine's full NixOS config"
for machine in machines/*/; do
  m="$(basename "$machine")"
  sed -e "s!@HOST@!$m!; s!@PASSWD@!\$6\$dummy\$dummy!" \
    configuration.nix.dist > "$work/configuration.nix"
  cp "machines/$m/hardware-configuration.nix" "$work/hardware-configuration.nix"

  if out=$(nix-instantiate '<nixpkgs/nixos>' -A system \
    -I "nixos-config=$work/configuration.nix" --argstr system "$SYSTEM" 2>&1); then
    printf '  ✓ %-6s %s\n' "$m" "$(echo "$out" | grep -o '/nix/store/[^ ]*\.drv')"
  else
    printf '  ✗ %-6s does not evaluate\n' "$m"
    echo "$out" | grep -E 'error:' | head -5 | sed 's/^/      /'
    fail=1
  fi
done

step "ruff + mypy --strict (operational Python)"
ruff check . 2>&1 | sed 's/^/  /'
[ "${PIPESTATUS[0]}" -eq 0 ] || fail=1
mypy --strict machines/amun/vpn-nodes-push.py machines/odin/backup_preview.py 2>&1 | sed 's/^/  /'
[ "${PIPESTATUS[0]}" -eq 0 ] || fail=1

step "pytest (operational Python)"
python -m pytest -q machines 2>&1 | sed 's/^/  /'
[ "${PIPESTATUS[0]}" -eq 0 ] || fail=1

step "shellcheck (host-side shell scripts)"
# shellcheck disable=SC2046  # word-splitting the file list is intended.
shellcheck $(git ls-files '*.sh') 2>&1 | sed 's/^/  /'
[ "${PIPESTATUS[0]}" -eq 0 ] || fail=1

step "dev-lint"
nix run "$HOME/Code/dev-lint" -- . 2>&1 | sed 's/^/  /'
[ "${PIPESTATUS[0]}" -eq 0 ] || fail=1

if [ "$fail" -ne 0 ]; then
  printf '\n✗ verify failed\n'
  exit 1
fi
printf '\n✓ verify passed\n'
